import { randomUUID } from 'node:crypto';

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { generateText } from 'ai';
import { MockLanguageModelV4 } from 'ai/test';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import type { Generate } from '@/modules/agents';
import { getBlock, updateBlock } from '@/modules/blocks';
import { saveNoteDocument } from '@/modules/notes';
import {
  acceptPreview,
  discardDerivation,
  getNoteSummary,
  getReviewQueue,
  getStaleCount,
  keepOldVersion,
  previewDerivation,
  resolveSources,
  runDerivation,
  summariseNote,
  type EngineContext,
} from '@/modules/recalc';
import { ensureWorkspace } from '@/modules/workspaces';
import { createBlock } from '@/modules/blocks';

// The slice-11 tests. `staleness.test.ts` and `tiptap-staleness.test.ts` prove
// the trigger by writing derivation rows with raw SQL, because the module did
// not exist yet. This proves the same invariant through the module that now
// does — a summary generated by the engine, edited underneath, and brought back.
//
// It runs against the real Supabase project with the service-role key, for the
// reason docs/DECISIONS.md gives: the cascade is a Postgres trigger and mocking
// it would test nothing. A throwaway auth user is created and deleted, which
// cascades to the workspace, its blocks, its derivations and their receipts.
//
// The ONE thing faked is the provider's network. There is no API key on this
// machine, so `runDerivation` is handed a `generate` that runs the real AI SDK
// `generateText` over the SDK's own `MockLanguageModelV4`. Everything under
// test — the status transitions, the receipt bookkeeping, the write through
// modules/blocks, the cascade — is the real thing, against the real database.
// The one place the *default* path is exercised (no `generate` passed at all,
// so the real registry is asked for the `deep` role) is the failure test, which
// is honest precisely because no key is configured.

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!url || !serviceKey) {
  throw new Error(
    'recalc-engine.test.ts needs NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY ' +
      'in .env.local, and migrations applied (npm run db:push). See SETUP.md.'
  );
}

// ---------------------------------------------------------------------------
// A model that does not exist
// ---------------------------------------------------------------------------

const NO_USAGE = {
  inputTokens: { total: 0, noCache: 0, cacheRead: 0, cacheWrite: 0 },
  outputTokens: { total: 0, text: 0, reasoning: 0 },
};

const STOPPED = { unified: 'stop' as const, raw: 'stop' };

/** The AI SDK call, for real, over a model that answers from memory. */
function fakeDeepRole(answer: () => string): Generate {
  return async ({ system, prompt }) => {
    const { text } = await generateText({
      model: new MockLanguageModelV4({
        provider: 'mock',
        modelId: 'mock-deep',
        doGenerate: async () => ({
          content: [{ type: 'text' as const, text: answer() }],
          finishReason: STOPPED,
          usage: NO_USAGE,
          warnings: [],
        }),
      }),
      ...(system ? { system } : {}),
      prompt,
    });

    return { text, model: 'mock/mock-deep' };
  };
}

/** A provider that is reachable and refuses. */
const brokenDeepRole: Generate = async () => {
  throw new Error('mock provider: 401 invalid api key');
};

// ---------------------------------------------------------------------------

const text = (value: string) => ({ type: 'text', text: value });
const paragraph = (blockId: string, value: string) => ({
  type: 'paragraph',
  attrs: { blockId },
  content: [text(value)],
});

const FIRST = 'Mitochondria are the powerhouse of the cell.';
const SECOND = 'They have their own DNA.';

describe('the recalc engine', () => {
  let db: SupabaseClient;
  let userId: string;
  let ctx: EngineContext;

  // A second workspace, owned by somebody else. Every ownership check is
  // proved against it.
  let strangerUserId: string;
  let strangerNoteId: string;
  let strangerDerivationId: string;

  let docId: string;
  let firstParagraph: string;
  let secondParagraph: string;

  let summary = 'A summary of cell biology, written by nothing at all.';
  const deepRole = fakeDeepRole(() => summary);

  async function makeNote(client: SupabaseClient, workspaceId: string) {
    const doc = await createBlock(client, {
      workspaceId,
      type: 'note',
      content: { text: 'Cell biology, lecture 4' },
    });

    const one = randomUUID();
    const two = randomUUID();
    await saveNoteDocument(client, workspaceId, doc.id, {
      nodes: [paragraph(one, FIRST), paragraph(two, SECOND)],
    });

    return { docId: doc.id, one, two };
  }

  async function statusOf(derivationId: string): Promise<string> {
    const { data, error } = await db
      .from('derivations')
      .select('status')
      .eq('id', derivationId)
      .single();
    if (error) throw new Error(error.message);
    return data.status;
  }

  async function receipt(derivationId: string) {
    const rows = await resolveSources(db, derivationId);
    return new Map(rows.map(({ row }) => [row.source_block_id, row]));
  }

  beforeAll(async () => {
    db = createClient(url, serviceKey, {
      auth: { persistSession: false, autoRefreshToken: false },
    });

    const mine = await db.auth.admin.createUser({
      email: `recalc-engine-test-${randomUUID()}@example.com`,
      email_confirm: true,
    });
    if (mine.error) throw new Error(`could not create test user: ${mine.error.message}`);
    userId = mine.data.user.id;

    const workspace = await ensureWorkspace(db, userId);
    ctx = { workspaceId: workspace.id, userId };

    const note = await makeNote(db, workspace.id);
    docId = note.docId;
    firstParagraph = note.one;
    secondParagraph = note.two;

    // Somebody else's note, with somebody else's summary on it.
    const stranger = await db.auth.admin.createUser({
      email: `recalc-stranger-test-${randomUUID()}@example.com`,
      email_confirm: true,
    });
    if (stranger.error) throw new Error(`could not create stranger: ${stranger.error.message}`);
    strangerUserId = stranger.data.user.id;

    const strangerWorkspace = await ensureWorkspace(db, strangerUserId);
    const strangerNote = await makeNote(db, strangerWorkspace.id);
    strangerNoteId = strangerNote.docId;

    const theirs = await summariseNote(
      db,
      { workspaceId: strangerWorkspace.id, userId: strangerUserId },
      strangerNoteId,
      { generate: fakeDeepRole(() => 'Not your summary.') }
    );
    if (!theirs.ok) throw new Error(`stranger setup failed: ${theirs.error}`);
    strangerDerivationId = theirs.derivationId;
  });

  afterAll(async () => {
    // Deleting the users cascades to workspaces, blocks, derivations and
    // derivation_sources. Nothing of this test is left in the project.
    if (db && userId) await db.auth.admin.deleteUser(userId);
    if (db && strangerUserId) await db.auth.admin.deleteUser(strangerUserId);
  });

  // -------------------------------------------------------------------------

  describe('summarising a note', () => {
    let derivationId: string;

    it('writes a summary block, a derivation and a complete receipt', async () => {
      const result = await summariseNote(db, ctx, docId, { generate: deepRole });
      expect(result.ok, result.ok ? '' : result.error).toBe(true);
      if (!result.ok) return;

      derivationId = result.derivationId;
      expect(result.text).toBe(summary);
      expect(await statusOf(derivationId)).toBe('fresh');

      const stored = await getNoteSummary(db, ctx.workspaceId, docId);
      expect(stored?.text).toBe(summary);
      expect(stored?.status).toBe('fresh');
      // The audit column is what actually answered, never a name chosen in app
      // code (CLAUDE.md, Never rule 6).
      expect(stored?.model).toBe('mock/mock-deep');
      expect(stored?.computedAt).not.toBeNull();

      // Every block the recipe read is on the receipt: the note document and
      // BOTH paragraphs. An under-recorded source is a staleness bug that stays
      // invisible until someone edits that exact block.
      const rows = await receipt(derivationId);
      expect([...rows.keys()].sort()).toEqual([docId, firstParagraph, secondParagraph].sort());
      expect(rows.get(firstParagraph)?.source_version).toBe(1);
      expect(rows.get(firstParagraph)?.source_text).toBe(FIRST);
    });

    it('is safe to run twice: one summary block, not two', async () => {
      const before = await getNoteSummary(db, ctx.workspaceId, docId);

      summary = 'A second answer, from the same fake model.';
      const again = await summariseNote(db, ctx, docId, { generate: deepRole });
      expect(again.ok).toBe(true);

      const after = await getNoteSummary(db, ctx.workspaceId, docId);
      expect(after?.blockId).toBe(before?.blockId);
      expect(after?.derivationId).toBe(before?.derivationId);
      expect(after?.text).toBe(summary);

      // And there is exactly one summary block in the whole workspace.
      const { data } = await db
        .from('blocks')
        .select('id')
        .eq('workspace_id', ctx.workspaceId)
        .eq('type', 'summary')
        .is('deleted_at', null);
      expect(data).toHaveLength(1);
    });

    it('refuses a note belonging to someone else, and writes nothing', async () => {
      await expect(summariseNote(db, ctx, strangerNoteId, { generate: deepRole })).rejects.toThrow(
        /no note/
      );

      // Still one summary in the stranger's workspace, and none of ours over there.
      const { data } = await db
        .from('derivations')
        .select('id')
        .eq('workspace_id', ctx.workspaceId);
      expect(data).toHaveLength(1);
    });
  });

  // -------------------------------------------------------------------------
  // THE invariant, through this module rather than through raw SQL.
  // -------------------------------------------------------------------------

  describe('the cascade', () => {
    it('a whitespace-only edit stales nothing', async () => {
      const summaryRow = await getNoteSummary(db, ctx.workspaceId, docId);
      expect(summaryRow?.status).toBe('fresh');

      await saveNoteDocument(db, ctx.workspaceId, docId, {
        nodes: [
          paragraph(firstParagraph, '  Mitochondria   are the powerhouse of the cell. '),
          paragraph(secondParagraph, SECOND),
        ],
      });

      expect((await getBlock(db, firstParagraph))?.version).toBe(1);
      expect(await statusOf(summaryRow!.derivationId)).toBe('fresh');
      expect(await getStaleCount(db, ctx.workspaceId)).toBe(0);
    });

    it('a real edit to a source marks its derivation stale', async () => {
      const summaryRow = await getNoteSummary(db, ctx.workspaceId, docId);

      await saveNoteDocument(db, ctx.workspaceId, docId, {
        nodes: [
          paragraph(firstParagraph, 'Mitochondria are NOT the powerhouse of the cell.'),
          paragraph(secondParagraph, SECOND),
        ],
      });

      expect((await getBlock(db, firstParagraph))?.version).toBe(2);
      expect(await statusOf(summaryRow!.derivationId)).toBe('stale');
      expect(await getStaleCount(db, ctx.workspaceId)).toBe(1);
    });

    it('/review says which source changed, with the words on both sides', async () => {
      const queue = await getReviewQueue(db, ctx.workspaceId);
      expect(queue).toHaveLength(1);

      const item = queue[0];
      expect(item.recipe).toBe('summarize');
      expect(item.note?.blockId).toBe(docId);
      expect(item.currentText).toBe(summary);

      const changed = item.sources.filter((source) => source.changed);
      expect(changed).toHaveLength(1);
      expect(changed[0].blockId).toBe(firstParagraph);
      expect(changed[0].readVersion).toBe(1);
      expect(changed[0].currentVersion).toBe(2);
      expect(changed[0].before).toBe(FIRST);
      expect(changed[0].after).toBe('Mitochondria are NOT the powerhouse of the cell.');

      // The unchanged paragraph is listed too, and is not flagged.
      const untouched = item.sources.find((source) => source.blockId === secondParagraph);
      expect(untouched?.changed).toBe(false);
    });
  });

  // -------------------------------------------------------------------------

  describe('regenerating', () => {
    it('previews without writing anything', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);

      const previewed = await previewDerivation(
        db,
        ctx,
        stored!.derivationId,
        { generate: fakeDeepRole(() => 'A preview nobody accepted.') }
      );
      expect(previewed.ok).toBe(true);

      // Still stale, still the old text, still the old receipt.
      expect(await statusOf(stored!.derivationId)).toBe('stale');
      const after = await getNoteSummary(db, ctx.workspaceId, docId);
      expect(after?.text).toBe(stored!.text);
      expect((await receipt(stored!.derivationId)).get(firstParagraph)?.source_version).toBe(1);
    });

    it('writes the new source versions and goes back to fresh', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);

      summary = 'Mitochondria are not, in fact, the powerhouse of the cell.';
      const result = await runDerivation(db, ctx, stored!.derivationId, { generate: deepRole });

      expect(result.ok, result.ok ? '' : result.error).toBe(true);
      expect(await statusOf(stored!.derivationId)).toBe('fresh');
      expect((await getNoteSummary(db, ctx.workspaceId, docId))?.text).toBe(summary);

      // The receipt now names version 2 of the paragraph that moved, and its
      // new words — which is what makes the *next* edit stale it again.
      const rows = await receipt(stored!.derivationId);
      expect(rows.get(firstParagraph)?.source_version).toBe(2);
      expect(rows.get(firstParagraph)?.source_text).toBe(
        'Mitochondria are NOT the powerhouse of the cell.'
      );
      expect(rows.get(secondParagraph)?.source_version).toBe(1);
      expect(await getStaleCount(db, ctx.workspaceId)).toBe(0);
    });

    it('stales again on the next real edit — the loop closes', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);

      await saveNoteDocument(db, ctx.workspaceId, docId, {
        nodes: [
          paragraph(firstParagraph, 'Mitochondria are NOT the powerhouse of the cell.'),
          paragraph(secondParagraph, 'They have their own circular DNA.'),
        ],
      });

      expect((await getBlock(db, secondParagraph))?.version).toBe(2);
      expect(await statusOf(stored!.derivationId)).toBe('stale');
    });

    it('accepts a preview, writing exactly the text that was shown', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);
      const ACCEPTED = 'Mitochondria are not the powerhouse; they carry circular DNA.';

      const previewed = await previewDerivation(db, ctx, stored!.derivationId, {
        generate: fakeDeepRole(() => ACCEPTED),
      });
      expect(previewed.ok).toBe(true);
      if (!previewed.ok) return;

      const accepted = await acceptPreview(db, ctx, {
        derivationId: previewed.preview.derivationId,
        text: previewed.preview.text,
        sources: previewed.preview.sources,
      });

      expect(accepted.ok, accepted.ok ? '' : accepted.error).toBe(true);
      expect(await statusOf(stored!.derivationId)).toBe('fresh');

      const after = await getNoteSummary(db, ctx.workspaceId, docId);
      expect(after?.text).toBe(ACCEPTED);
      expect((await receipt(stored!.derivationId)).get(secondParagraph)?.source_version).toBe(2);
    });

    it('refuses a preview whose note moved on underneath it', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);

      const previewed = await previewDerivation(db, ctx, stored!.derivationId, {
        generate: fakeDeepRole(() => 'Generated before the edit.'),
      });
      expect(previewed.ok).toBe(true);
      if (!previewed.ok) return;

      // The note changes between the preview and the accept.
      await saveNoteDocument(db, ctx.workspaceId, docId, {
        nodes: [
          paragraph(firstParagraph, 'Mitochondria make ATP, and that is the whole story.'),
          paragraph(secondParagraph, 'They have their own circular DNA.'),
        ],
      });

      const accepted = await acceptPreview(db, ctx, {
        derivationId: previewed.preview.derivationId,
        text: previewed.preview.text,
        sources: previewed.preview.sources,
      });

      expect(accepted.ok).toBe(false);
      if (accepted.ok) return;
      expect(accepted.error).toMatch(/changed again/);

      // Refused means untouched: the old summary stands and the row is stale.
      expect(await statusOf(stored!.derivationId)).toBe('stale');
      expect((await getNoteSummary(db, ctx.workspaceId, docId))?.text).toBe(stored!.text);
    });
  });

  // -------------------------------------------------------------------------

  describe('a failed model call', () => {
    it('leaves the derivation at error, never at computing', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);

      const result = await runDerivation(db, ctx, stored!.derivationId, {
        generate: brokenDeepRole,
      });

      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error).toMatch(/401/);

      expect(await statusOf(stored!.derivationId)).toBe('error');

      const { data } = await db
        .from('derivations')
        .select('error')
        .eq('id', stored!.derivationId)
        .single();
      expect(data?.error).toMatch(/401/);
    });

    it('leaves it at error when no model is configured at all — the real path', async () => {
      // No `generate` is passed, so worker.ts asks modules/agents for the
      // `deep` role for real. This user has no agent_profiles row, so the
      // registry throws AgentNotConfigured. That is the failure mode a person
      // who has not pasted a key yet will actually hit.
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);

      const result = await runDerivation(db, ctx, stored!.derivationId);

      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error).toMatch(/deep/i);
      expect(await statusOf(stored!.derivationId)).toBe('error');
    });

    it('never writes over the summary that was already there', async () => {
      const after = await getNoteSummary(db, ctx.workspaceId, docId);
      expect(after?.text).toBe('Mitochondria are not the powerhouse; they carry circular DNA.');
    });
  });

  // -------------------------------------------------------------------------

  describe('the three answers /review offers', () => {
    it('"keep old" leaves the text alone and moves the receipt forward', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);
      const derivationId = stored!.derivationId;
      const derivedBlockId = stored!.blockId;
      const before = await getBlock(db, derivedBlockId);

      // Put it back in a stale-shaped state first: a run that succeeds, then an
      // edit that stales it.
      summary = 'A summary that will be kept as it is.';
      await runDerivation(db, ctx, derivationId, { generate: deepRole });
      await saveNoteDocument(db, ctx.workspaceId, docId, {
        nodes: [
          paragraph(firstParagraph, 'Mitochondria make ATP, and they are fascinating.'),
          paragraph(secondParagraph, 'They have their own circular DNA.'),
        ],
      });
      expect(await statusOf(derivationId)).toBe('stale');

      const kept = await keepOldVersion(db, ctx, derivationId);
      expect(kept.ok).toBe(true);

      // Fresh again, the summary untouched, and its own version not bumped —
      // so nothing downstream of the summary was disturbed either.
      expect(await statusOf(derivationId)).toBe('fresh');
      const after = await getBlock(db, derivedBlockId);
      expect(after?.content.text).toBe(summary);
      expect(after?.version).toBe(before!.version + 1);

      // The receipt now names the version the person actually looked at, so the
      // next edit stales it again rather than it nagging forever.
      const current = (await getBlock(db, firstParagraph))!.version;
      expect((await receipt(derivationId)).get(firstParagraph)?.source_version).toBe(current);
      expect(await getStaleCount(db, ctx.workspaceId)).toBe(0);
    });

    it('"keep old" is not a way to freeze a summary: the next edit stales it', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);

      await saveNoteDocument(db, ctx.workspaceId, docId, {
        nodes: [
          paragraph(firstParagraph, 'Mitochondria make ATP by oxidative phosphorylation.'),
          paragraph(secondParagraph, 'They have their own circular DNA.'),
        ],
      });

      expect(await statusOf(stored!.derivationId)).toBe('stale');
    });

    it('refuses every action on somebody else\'s derivation', async () => {
      await expect(runDerivation(db, ctx, strangerDerivationId, { generate: deepRole })).rejects.toThrow(
        /no derivation/
      );
      await expect(previewDerivation(db, ctx, strangerDerivationId)).rejects.toThrow(
        /no derivation/
      );
      await expect(
        acceptPreview(db, ctx, { derivationId: strangerDerivationId, text: 'mine now', sources: [] })
      ).rejects.toThrow(/no derivation/);
      await expect(keepOldVersion(db, ctx, strangerDerivationId)).rejects.toThrow(
        /no derivation/
      );
      await expect(discardDerivation(db, ctx, strangerDerivationId)).rejects.toThrow(
        /no derivation/
      );

      // And none of that touched it: still fresh, still their words.
      expect(await statusOf(strangerDerivationId)).toBe('fresh');
      const { data } = await db
        .from('derivations')
        .select('derived_block_id')
        .eq('id', strangerDerivationId)
        .single();
      const block = await getBlock(db, data!.derived_block_id);
      expect(block?.content.text).toBe('Not your summary.');
      expect(block?.deleted_at).toBeNull();
    });

    it('"delete" soft-deletes the block and removes the derivation', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);
      const { derivationId, blockId } = stored!;

      await discardDerivation(db, ctx, derivationId);

      expect(await getNoteSummary(db, ctx.workspaceId, docId)).toBeNull();
      expect(await getStaleCount(db, ctx.workspaceId)).toBe(0);
      expect(await getReviewQueue(db, ctx.workspaceId)).toEqual([]);

      // The block is soft-deleted, never destroyed: provenance outlives it.
      const block = await getBlock(db, blockId);
      expect(block).not.toBeNull();
      expect(block?.deleted_at).not.toBeNull();

      const { data } = await db.from('derivations').select('id').eq('id', derivationId);
      expect(data).toEqual([]);
    });

    it('summarising again after a delete makes a new one rather than resurrecting', async () => {
      summary = 'A brand new summary after the old one was thrown away.';
      const result = await summariseNote(db, ctx, docId, { generate: deepRole });

      expect(result.ok, result.ok ? '' : result.error).toBe(true);
      expect((await getNoteSummary(db, ctx.workspaceId, docId))?.text).toBe(summary);
    });
  });

  // -------------------------------------------------------------------------

  describe('an edit that lands while a run is in flight', () => {
    it('finishes stale rather than claiming to be current', async () => {
      const stored = await getNoteSummary(db, ctx.workspaceId, docId);
      expect(stored?.status).toBe('fresh');

      // The trigger only touches rows whose status is `fresh`, and a running
      // derivation says `computing` — so an edit made during the call is
      // invisible to it. The worker re-reads the versions afterwards for
      // exactly this case.
      const slowRole: Generate = async () => {
        await updateBlock(db, firstParagraph, {
          content: {
            type: 'paragraph',
            attrs: { blockId: firstParagraph },
            content: [text('Edited while the model was thinking.')],
          },
        });
        return { text: 'A summary of notes that changed underneath it.', model: 'mock/mock-deep' };
      };

      const result = await runDerivation(db, ctx, stored!.derivationId, { generate: slowRole });
      expect(result.ok).toBe(true);

      expect(await statusOf(stored!.derivationId)).toBe('stale');
      expect(await getStaleCount(db, ctx.workspaceId)).toBe(1);
    });
  });
});
