// Public API of the courses module. Import only from here.
export {
  getCourses,
  getCourse,
  getSessions,
  getSession,
  getSyllabusUnits,
  getMeeting,
  getMeetingsOnDate,
  getMeetingsBetween,
  getMeetingsForSession,
  getMeetingsWithNotes,
  generateMeetings,
  meetingWasHandEdited,
  rescheduleMeeting,
  setMeetingStatus,
  setMeetingNote,
  setMeetingUnit,
  createCourse,
  createSession,
  updateSession,
  removeSession,
  removeMeetings,
  createOneOffMeeting,
  createSyllabusUnit,
  renameSyllabusUnit,
  setSyllabusUnitStatus,
  reorderSyllabusUnits,
  moveSyllabusUnit,
} from './service';
export {
  courseSchema,
  courseCodeSchema,
  courseNameSchema,
  sessionSchema,
  syllabusUnitSchema,
  classMeetingSchema,
  meetingStatusSchema,
  syllabusUnitStatusSchema,
  syllabusUnitTitleSchema,
  createCourseInputSchema,
  createSessionInputSchema,
  updateSessionInputSchema,
  createSyllabusUnitInputSchema,
  unitMoveSchema,
  weekdaySchema,
  type Course,
  type Session,
  type SyllabusUnit,
  type SyllabusUnitStatus,
  type CreateCourseInput,
  type CreateSessionInput,
  type UpdateSessionInput,
  type CreateSyllabusUnitInput,
  type UnitMove,
  type ClassMeeting,
  type MeetingStatus,
  type GenerateMeetingsInput,
  type GenerateMeetingsResult,
  type CreateOneOffMeetingInput,
  type RescheduleMeetingInput,
} from './schema';
