// Public API of the courses module. Import only from here.
export {
  getCourses,
  getSyllabusUnits,
  getMeeting,
  getMeetingsOnDate,
  getMeetingsBetween,
  generateMeetings,
  rescheduleMeeting,
  setMeetingStatus,
  createOneOffMeeting,
} from './service';
export {
  courseSchema,
  sessionSchema,
  syllabusUnitSchema,
  classMeetingSchema,
  meetingStatusSchema,
  syllabusUnitStatusSchema,
  weekdaySchema,
  type Course,
  type Session,
  type SyllabusUnit,
  type SyllabusUnitStatus,
  type ClassMeeting,
  type MeetingStatus,
  type GenerateMeetingsInput,
  type GenerateMeetingsResult,
  type CreateOneOffMeetingInput,
  type RescheduleMeetingInput,
} from './schema';
